### ISSUE TITLE
Remake OperatingReport from current MonthlyOperatingReport

### ISSUE THREAD

**Issue by cwhanse** [Open-Orange-Button/Orange-Button-Taxonomy#102]
After #101 is merged.

**Comment by THagen-BB** [comment]
Covered under issue #128 (Create Operating Report)

**Comment by cwhanse** [comment]
When remade, attach Production and FileFolderURL

**Comment by cwhanse** [comment]
Requires creation of Revenue and Expense objects

**Comment by cwhanse** [comment]
Add array of object for Operations and Maintenance Event

**Comment by cwhanse** [comment]
Add array elements for PowerFactor, Curtailment

**Comment by cwhanse** [comment]
Add unit for kWhr per kWp, so that we can report capacity-normalized yield
