### ISSUE TITLE
2212.0.0 release planning

### ISSUE THREAD

**Issue by cwhanse** [Open-Orange-Button/Orange-Button-Taxonomy#160]
- [x] #94 
- [x] #95 
- [x] #96 
- [ ] #151 
- ~~[ ] #119~~ - partially complete, rest is deferred 
- ~~[ ] #159~~ - partially complete, rest is deferred
- [x] #39 
- [x] #61 
- [x] #129 
- [ ] #137 
- [ ] #55 
- ~~[ ] #57~~ - deferred

**Comment by cwhanse** [comment]
I will take #119, #159, #61, #129

**Comment by kevinkirkl3y** [comment]
I will work with @THagen-BB to work on #96. For #95 I think we need some clarification on what the ask is here, is it as simple as removing the enumerations corresponding to Elements we have created in the taxonomy?

**Comment by cwhanse** [comment]
Closing due to 2305.0.0 release, in favor of a new issue to track the next release.
