### ISSUE TITLE
Date/Time formatting ISO 8601

### ISSUE THREAD

**Issue by THagen-BB** [Open-Orange-Button/Orange-Button-Taxonomy#166]
Ensure that all date/time fields have examples that are compliant with ISO 8601 standard

**Comment by cwhanse** [comment]
Consider restricting per RFC 3339, https://datatracker.ietf.org/doc/html/rfc3339

**Comment by kevinkirkl3y** [comment]
Create DateTimeItemType. Clean up DateItemType sample values to only include Date string.

**Comment by kevinkirkl3y** [comment]
Close #179
