### ISSUE TITLE
Revisit Warranty, PowerWarranty, ProductWarranty

### ISSUE THREAD

**Issue by cwhanse** [Open-Orange-Button/Orange-Button-Taxonomy#175]
When we do this, be careful to distinguish between product warranty conditions and an instance of the warranty, which has an effective and expiration date. 

The idea is that a Warranty (as currently composed) associates with a Device, and the general terms (new object ProdWarranty?) are associated with a Product.

**Comment by kevinkirkl3y** [comment]
Update WarrantyDuration to TaxonomyElementNumber.

**Comment by cwhanse** [comment]
Replace WarrantyDuration with Duration

**Comment by cwhanse** [comment]
Resolved via #246
