### ISSUE TITLE
Update the ProdCode documentation and sample value

### ISSUE THREAD

**Issue by kevinkirkl3y** [Open-Orange-Button/Orange-Button-Taxonomy#181]
Using the same product set as the sample for ProdName. "Q.PEAK DUO BLK-G10+/AC 365"

Anything that is not a letter or number is a special character.

All letters are upper-case.

In cases of clashes with identical ProdCode append {ProdCode}-{incremental number}.

**Comment by kevinkirkl3y** [comment]
#170

**Comment by cwhanse** [comment]
Closed by #186
