### ISSUE TITLE
Generate element that represents Labor type.

### ISSUE THREAD

**Issue by kevinkirkl3y** [Open-Orange-Button/Orange-Button-Taxonomy#203]
To meet the standards required by the IRA we need to capture specific information representing labor on a given project. We need to generate an element to represent this datapoint.

**Comment by THagen-BB** [comment]
From an insurance standpoint, this is what it appears we will need regarding labour data at this point:
number of employees per job
number of contractors per job
number of hours it took to complete the physical installation

**Comment by kevinkirkl3y** [comment]
Record time entries against a contract

**Comment by kevinkirkl3y** [comment]
Associate a Laborer with the Contract via LaborerID.

Rename object, Laborer carries too much background context? Worker

Inherit from Contact? Phillip wouldn't say yes. 

Need clarity of the requirements of what information is needed for the Tax Credit.

**Comment by kevinkirkl3y** [comment]
Closed #205
