### ISSUE TITLE
Draft element that represents CustomElements between two systems. 

### ISSUE THREAD

**Issue by kevinkirkl3y** [Open-Orange-Button/Orange-Button-Taxonomy#223]
Pair of names and Common value:

Use case being: Allows sharing of data that is not included within the OB taxonomy without additional development of the taxonomy itself.

**Comment by kevinkirkl3y** [comment]
Data type included in object.

**Comment by naulacambra** [comment]
It would be nice if the pairs could be grouped into clusters, with each cluster having a defined scope/key. This would make it easier to manage the authorization of such data.

Use case: A centralized repository, which is used by different applications, each of which needs additional data, different from each other. Each application should be able to request its own data.

**Comment by kevinkirkl3y** [comment]
Closed #224
