### ISSUE TITLE
Review ProductWarranty and ModulePerfWarrGuaranteedOutput

### ISSUE THREAD

**Issue by kevinkirkl3y** [Open-Orange-Button/Orange-Button-Taxonomy#225]
We need to generate elements that match the current OB development to share the data points represented by these XBRL developed elements.

**Comment by cwhanse** [comment]
ProductWarranty is likely redundant with the Warranty object.

**Comment by kevinkirkl3y** [comment]
Purge non-essential, unused Warranty/Guarantee elements to limit confusion. 
 ModulePerfWarrGuaranteedOutput

**Comment by cwhanse** [comment]
Closed via #246
