### ISSUE TITLE
OB Taxonomy Checker Not Running Custom Rules with Current Dependency Versions

### ISSUE THREAD

**Issue by cwhanse** [Open-Orange-Button/Orange-Button-Taxonomy#26]
See #25 for details

**Comment by reepoi** [comment]
The current OB Taxonomy Checker using IBM OpenAPI Validator version 0.52.1 has stopped running the custom validation rules in the .spectral.yaml configuration file. The custom validation rules will run with IBM OpenAPI Validator version 0.76.2. Pull request #59 updates the OB Taxonomy Checker to use this version.

**Comment by cwhanse** [comment]
@reepoi is this issue closed?

**Comment by reepoi** [comment]
yes, this was closed by #59.
