### ISSUE TITLE
Consider linking FailureRecord with LossReport

### ISSUE THREAD

**Issue by cwhanse** [Open-Orange-Button/Orange-Button-Taxonomy#288]
LossReport has an enumeration including Failure and Inoperative. We could add a link to the FailureRecord for these events.

**Comment by jrippingale** [comment]
Perhaps the way to link this would be to Add the Issue object to EnergyLoss object

**Comment by cwhanse** [comment]
Resolved by deciding that OMIssue is primary and has both EnergyLoss and FailureRecords as members.
