### ISSUE TITLE
Update EntityRoleItemType enum list/Create and Update CertificationAgency elements 

### ISSUE THREAD

**Issue by kevinkirkl3y** [Open-Orange-Button/Orange-Button-Taxonomy#302]
Add:
- [ ] CertificationAgency
- [ ] TestingLab/Assessor

CertificationAgency needs to be updated to inherit from Entity, clean up duplicate members. 

@alftom @cwhanse @jrippingale Please add additional notes on this issue to define required changes.

**Comment by cwhanse** [comment]
Closed by #305
