### ISSUE TITLE
Add "Grid-Capable" enum object

### ISSUE THREAD

**Issue by blizita** [Open-Orange-Button/Orange-Button-Taxonomy#39]
Create an "GridInterfaceType" enum object and attach to ProdInverter and ProdEnergyStorageSystem

Enum list:
Grid-Following
Islanding Capable
Off-Grid Only
(Maybe something else?)

**Comment by jrippingale** [comment]
![image](https://user-images.githubusercontent.com/19517827/206809514-11614940-13bd-40f1-8247-2e14bd70db47.png)

This is done.

**Comment by jrippingale** [comment]
This is done with GridInterfaceType unit, element and is included in ProdInverter and ProdEnergyStorageSystem.
