### ISSUE TITLE
Add CEC Data to ProdBattery

### ISSUE THREAD

**Issue by blizita** [Open-Orange-Button/Orange-Button-Taxonomy#55]
[Energy_Storage_System_List_Data_ADA (1).xlsx](https://github.com/Open-Orange-Button/Orange-Button-Taxonomy/files/8612859/Energy_Storage_System_List_Data_ADA.1.xlsx)

We need to add some objects to prodBattery to hold CEC values (see attached sheet). It looks like there will be one Array and a couple individual objects.

To do: The CEC Sheet lists "Nameplate Capacity" and "Max Continuous Discharge Rate". Are these values manufacture reported or CEC test results. (If they are test results we need to create objects to hold them).

**Comment by kevinkirkl3y** [comment]
@blizita

**Comment by cwhanse** [comment]
Completed via #249
