### ISSUE TITLE
Take a look a naming scheme for ProdSolarCell.CellTechnologyType Enum

### ISSUE THREAD

**Issue by blizita** [Open-Orange-Button/Orange-Button-Taxonomy#61]
Based on our discussion on `batteryChemistryItemType` we should revisit the Enum naming scheme for `cellTechnologyItemType`

**Comment by kevinkirkl3y** [comment]
@blizita

**Comment by cwhanse** [comment]
Possibly closed by #197

**Comment by cwhanse** [comment]
Decision in #197 is that CellTypeTechnologyItemType lists the cell junction type, but not its chemistry. Closing this issue, chemistry can be added but as a separate ItemType.
